# Generated by Django 3.1.4 on 2020-12-23 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0003_achievement'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=128)),
                ('achievements', models.ManyToManyField(to='games.Achievement')),
            ],
        ),
    ]
