# Generated by Django 3.1.4 on 2020-12-25 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_playeruser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playeruser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='playeruser',
            name='username',
        ),
    ]
