# Generated by Django 3.1.4 on 2020-12-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_game_description'),
        ('players', '0005_auto_20201225_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='playeruser',
            name='games',
            field=models.ManyToManyField(to='games.Game'),
        ),
    ]
