# Generated by Django 3.1.4 on 2021-02-10 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_game_description'),
        ('players', '0006_playeruser_games'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achiobtained',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateachieved', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.achievement')),
                ('playeruser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.playeruser')),
            ],
        ),
        migrations.AlterField(
            model_name='playeruser',
            name='achievements',
            field=models.ManyToManyField(through='players.Achiobtained', to='games.Achievement'),
        ),
    ]
