# Generated by Django 3.1.4 on 2020-12-23 23:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_achievement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='gamer_points',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
