# Generated by Django 3.1.4 on 2020-12-25 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
        migrations.RenameField(
            model_name='news',
            old_name='created_at',
            new_name='created',
        ),
        migrations.AddField(
            model_name='news',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
