# Generated by Django 3.1.4 on 2020-12-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_auto_20201225_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
